# Generated by Django 2.2.25 on 2021-12-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211207_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='name',
        ),
    ]
