# Generated by Django 2.2.25 on 2021-12-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211207_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='channel',
            name='name2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='playlist',
            name='name2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='watch',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='watch',
            name='name2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='watch',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
